### ISSUE TITLE
TypeError: Assignment to constant variable.

### ISSUE THREAD

**Issue by dfischbach** [zorce/socketcand-client#1]
The module is crashing when using node version 6.x or newer. 4.x is working.

TypeError: Assignment to constant variable.
    at EventEmitter.subscribe (../socketcand-client/socketcand.js:253:7)

scc is defined const but assigned a second time in an if case, which is unnecessary.

```
function subscribe(sockId, id, sec, usec) {
	const scc = getConnectionFromId(sockId);
	if (scc == undefined) {
		return new Error("Socket not found for id " + sockId);
	}

	if (state == Mode.BCM) {
		scc = getConnectionFromId(sockId);  // NOT NEEDED!
		scc.write('< subscribe '+sec+' '+usec+' '+id+' >');
	} else {
		return new Error('ERROR cannot subscribe, wrong state');
	}
}
```

**Comment by zorce** [comment]
Thanks for pointing this out! Update on the way
